
name: Pull Latest Data

on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run get.sh
      run: |
       cd data
       ./get.sh 
        
    - name: Commit files
      run: |
        git add --all
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "workflow: Automated data pull" | exit 0
    - name: Push changes
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
